### ISSUE TITLE
Sourcery regularly stuck in endless analysis loop

### ISSUE THREAD

**Issue by darkvertex** [sourcery-ai/sourcery-vscode#150]
I looooove Sourcery. It is a very helpful extension.

As of late while I'm using the "Remote SSH" official extension, it goes into a crazy endless loop of analysis and re-analysis wasting precious CPU cycles:
![Code_H34CvapXSx](https://github.com/sourcery-ai/sourcery-vscode/assets/941331/41064fb0-fc74-440d-b736-568a1068ad15)

Is there some way I can produce debug information for you to nail this bug?

**Comment by ruancomelli** [comment]
Hello, @darkvertex; thanks for reaching out! This is a very interesting bug...

I have a couple of questions/requests for you:

1. does this bug happen without the Remote SSH connection?
2. what version of VS Code, Operating System (both local and remote), and Sourcery are you running?
3. can you please share your [Sourcery log file](https://docs.sourcery.ai/Product/Troubleshooting/#what-is-the-sourcery-log) with support@sourcery.ai?
4. it seems that the issue is happening specifically in your `test_link_apis.py` file - have you noticed it happening with other files as well?

**Comment by ruancomelli** [comment]
Thank you, @darkvertex! I'll look into this issue and get back to you in case I need more information or get it fixed :smile:

**Comment by ruancomelli** [comment]
Hi again, @darkvertex!

As you suggested, it seems that many files are being opened and closed, triggering Sourcery reviews multiple times. Just note that Sourcery does _not_ open/close files for you - instead, a Sourcery review is triggered every time a file is opened via other means.

Could you share the extensions you have installed and enabled on VS Code? One of them might be refreshing files in a funny way, triggering all those reviews.

Additionally, do you always get this strange behavior, or have you noticed any pattern in your usage that causes it? That is, have you noticed if there is any action that you or any other tool perform that triggers this bug?

**Comment by darkvertex** [comment]
Hi!

After a little big of extra digging, I've narrowed this down to an issue with Pyright/Pylance going crazy and opening and closing files en masse, so I'm fairly certain this is not an actual bug with Sourcery, so I'm closing this issue.

I've since put a pyrightconfig.json file in my project with a lot of explicit exclusions and inclusions and it seems to have calmed down.

Thanks for looking at my problem. It helped me get to the real issue.
