### ISSUE TITLE
No refactoring suggestions on closed-source projects with an open-source plan

### ISSUE THREAD

**Issue by Ant1-21** [sourcery-ai/sourcery-vscode#239]
I dont't have any refactoring suggestions on vs-code on Ubuntu. Did I missed something ? Are refactoring suggestions in non-free version ?

**sourcery, version 1.13.0**

## Vscode

Version : 1.84.1
Validation : 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date : 2023-11-06T12:35:31.181Z
Electron : 25.9.2
ElectronBuildId : 24603566
Chromium : 114.0.5735.289
Node.js : 18.15.0
V8 : 11.4.183.29-electron.0
Système d’exploitation : Linux x64 6.2.0-35-generic snap

**Comment by Hellebore** [comment]
Hi! This is due to a recent change in how we charge for Sourcery. We've had a number of long discussions about this internally, and ultimately from a business perspective we've had to shift to have Sourcery be free for students and open source projects and paid for private projects.

If you click on the sourcery icon in the sidebar you can see your upgrade options:

<img width="484" alt="Screenshot 2023-11-09 at 10 05 00" src="https://github.com/sourcery-ai/sourcery-vscode/assets/3765186/32466840-3e66-4932-8241-7e01e997b8f5">


Sorry our communication around this change has not been clear enough - we'll be taking some steps shortly to improve on that front. Please get in touch with us at [hello@sourcery.ai](mailto:hello@sourcery.ai) if you have further questions or concerns.

**Comment by Ant1-21** [comment]
Hi,
Sadly, it was the only feature interesting for me.
I will find an alternative.
